// The 48 teams competing in the 2026 FIFA World Cup group stage
// (sourced from wc_data/wc_data/schedule_2026.csv).
export const TEAMS_2026 = [
  "Algeria",
  "Argentina",
  "Australia",
  "Austria",
  "Belgium",
  "Bosnia-Herzegovina",
  "Brazil",
  "Canada",
  "Cape Verde",
  "Colombia",
  "Congo DR",
  "Croatia",
  "Curaçao",
  "Czechia",
  "Côte d'Ivoire",
  "Ecuador",
  "Egypt",
  "England",
  "France",
  "Germany",
  "Ghana",
  "Haiti",
  "IR Iran",
  "Iraq",
  "Japan",
  "Jordan",
  "Korea Republic",
  "Mexico",
  "Morocco",
  "Netherlands",
  "New Zealand",
  "Norway",
  "Panama",
  "Paraguay",
  "Portugal",
  "Qatar",
  "Saudi Arabia",
  "Scotland",
  "Senegal",
  "South Africa",
  "Spain",
  "Sweden",
  "Switzerland",
  "Tunisia",
  "Türkiye",
  "United States",
  "Uruguay",
  "Uzbekistan",
] as const;

export type Team = (typeof TEAMS_2026)[number];
